<a href="https://colab.research.google.com/github/Adarsh-Saurabh/Libraries-Learning/blob/Python-Libraries/Code_with_Harry___Numpy__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Installing Numpy**


In [266]:
!pip install numpy 

In [267]:
import numpy as np

In [268]:
arr = np.array([3,6,32,7])

In [269]:
arr

array([ 3,  6, 32,  7])

In [270]:
arr = np.array([[3,6,32,7] ],       np.int32)    #This is a one dimensional array

In [271]:
arr

array([[ 3,  6, 32,  7]], dtype=int32)

In [272]:
arr[0,2]  #0th row and 3rd column

32

In [273]:
arr[0, 2] = 23       #changing the value of 3rd column to 23 from 32

In [274]:
arr

array([[ 3,  6, 23,  7]], dtype=int32)

In [275]:
arr.shape


(1, 4)

In [276]:
arr.dtype

dtype('int32')

#Array Creation:- Conversion from other Python structures

In [277]:
listarray = np.array([[1,2,3 ], [ 4,5,6 ], [5,5,8 ]] , np.int8)    #Making a 3 dimensional array

In [278]:
listarray.shape      #it is a 3 * 3 matrix

(3, 3)

In [279]:
listarray.size      #total no of elements in the list

9

*Making an array as a object*

In [280]:
np.array({43,32,32 , 54 , 54})

array({32, 43, 54}, dtype=object)

*Making an null array of 2,5* 

In [281]:
x = np.zeros((2,5))

In [282]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

New array

In [283]:
xy = np.arange(0,15)       #Making an array on no from 0 till 15 using 'arange'

In [284]:
xy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

*Making an equal spaced array

In [285]:
equalspace = np.linspace(1,5,12)    #in range 1 to 6 print 12 equal spaced no

In [286]:
equalspace


array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [287]:
equalspace2 = np.linspace(0,50,3)      #printing 3 equal spaced integers from 0 to 50

In [288]:
equalspace2

array([ 0., 25., 50.])

*Making an array of random values*

In [289]:
emp = np.empty((4,4))

In [290]:
emp

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [291]:
emp_like = np.empty_like(equalspace)

In [292]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

*Making an Identity Matrix *

In [293]:
ide = np.identity(4)

In [294]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

*Using reshape*

In [295]:
a = np.arange(99)

In [296]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [297]:
a.reshape(9,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [298]:
a = a.reshape(3,33)

In [299]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [300]:
a.shape


(3, 33)

In [301]:
a = a.ravel()  #converting to one dimensional array 

In [302]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [303]:
a.shape

(99,)

***Learning Axis***

For 2d array we need 2 axis

*axis starts from 0 if  the array is 2d then axis0 means column and axis1 means now*

In [304]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [305]:
y = np.array(x)

In [306]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [307]:
y.sum(axis = 0)

array([12,  8,  9])

In [308]:
y.sum(axis = 1)

array([ 6, 15,  8])

In [309]:
y.diagonal()

array([1, 5, 0])

In [316]:
y.T         #Taking transpose of the array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [317]:
for z in y.flat:   #Making iterable 
  print(z)

1
4
7
2
5
1
3
6
0


In [318]:
y.nbytes

72

In [319]:
one = np.array([1,3,4,4343,43])

In [321]:
one.argmax()   #printing the position of the largest no 

3

In [322]:
one.argmin()

0

In [323]:
one.argsort()   #sorting the array in ascending order

array([0, 1, 2, 4, 3])

In [326]:
y

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [324]:
y.argmin()

8

In [325]:
y.argmax()

2

In [327]:
y.argmax(axis = 0)

array([2, 2, 0])

In [328]:
y.argmin(axis = 1)

array([0, 2, 2])

In [331]:
y

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [334]:
y.argsort() 

array([[0, 1, 2],
       [2, 0, 1],
       [2, 0, 1]])

In [330]:
y.dtype

dtype('int64')

***Mathematical operation***

In [335]:
y*y


array([[ 1, 16, 49],
       [ 4, 25,  1],
       [ 9, 36,  0]])

In [338]:
(y*2*y+2)/3

array([[ 1.33333333, 11.33333333, 33.33333333],
       [ 3.33333333, 17.33333333,  1.33333333],
       [ 6.66666667, 24.66666667,  0.66666667]])

In [339]:
np.sqrt(y)

array([[1.        , 2.        , 2.64575131],
       [1.41421356, 2.23606798, 1.        ],
       [1.73205081, 2.44948974, 0.        ]])

In [344]:
np.where(y<5)

(array([0, 0, 1, 1, 2, 2]), array([0, 1, 0, 2, 0, 2]))